# Generated by Django 4.0.3 on 2022-08-01 09:15

import apps.product.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('description', models.CharField(max_length=100, verbose_name='説明')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格')),
                ('image', apps.product.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('max_sell', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='販売数の最大')),
                ('price_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='stripeのprice_ID')),
                ('arrow_duplicate_store', models.BooleanField(blank=True, default=False, verbose_name='店の重複を許すか')),
                ('stub_count', models.IntegerField(default=3, verbose_name='スタブの許容数')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
            ],
        ),
    ]
