# Generated by Django 4.0.3 on 2022-09-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_end_dt_product_sale_dt_product_start_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='arrow_duplicate_store',
            new_name='allow_duplicate_store',
        ),
    ]
