# Generated by Django 4.0.3 on 2022-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_arrow_duplicate_store_product_allow_duplicate_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.IntegerField(choices=[(0, 'evenly'), (1, 'one_by_one')], default=0, verbose_name='stubの使われ方'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stub_count',
            field=models.IntegerField(default=3, verbose_name='stubの許容数'),
        ),
    ]
