# Generated by Django 4.0.3 on 2022-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_usage_alter_product_stub_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default='', max_length=3000, verbose_name='利用規約'),
        ),
    ]
