# Generated by Django 4.2.3 on 2023-09-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stub_price',
            field=models.IntegerField(default=500, verbose_name='stubの単価'),
        ),
    ]
