# Generated by Django 4.2.3 on 2023-09-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_stub_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='questionnaire_url',
            field=models.URLField(blank=True, null=True, verbose_name='アンケート用リンク'),
        ),
    ]
