# Generated by Django 4.0.3 on 2022-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_followed',
            field=models.BooleanField(default=False, verbose_name='フォローされているか'),
        ),
    ]
