# Generated by Django 4.0.3 on 2022-08-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='lineAccount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
