# Generated by Django 4.0.3 on 2022-08-02 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_owner_lineaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owner_shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
