# Generated by Django 4.0.3 on 2022-08-11 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_owner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='lineAccount',
        ),
    ]
