# Generated by Django 4.0.3 on 2022-08-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_owner_lineaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
