# Generated by Django 4.0.3 on 2022-08-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stub_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='access',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='コメント'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='hour',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='営業時間'),
        ),
    ]
