# Generated by Django 4.0.3 on 2022-08-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_shop_access_alter_shop_comment_alter_shop_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='comment',
        ),
        migrations.AddField(
            model_name='shop',
            name='menu',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='shop',
            name='pictnum',
            field=models.IntegerField(blank=True, null=True, verbose_name='写真番号'),
        ),
    ]
