# Generated by Django 4.0.3 on 2022-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_shop_comment_shop_menu_shop_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='menu',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='メニュー'),
        ),
    ]
