# Generated by Django 4.0.3 on 2022-08-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_shop_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='altname',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='表示名'),
        ),
    ]
