# Generated by Django 4.0.3 on 2022-08-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_shop_altname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='gpsLatitude',
            field=models.FloatField(blank=True, help_text='degrees, floating point, South is negative', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='shop',
            name='gpsLongitude',
            field=models.FloatField(blank=True, help_text='degrees, floating point, West is negative', null=True, verbose_name='Longtitude'),
        ),
    ]
