# Generated by Django 4.0.3 on 2022-08-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_shop_gpslatitude_shop_gpslongitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='電話番号'),
        ),
    ]
