# Generated by Django 4.0.3 on 2022-08-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_shop_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='pictnum',
        ),
        migrations.AddField(
            model_name='shop',
            name='mpictID',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='メニュー写真ID'),
        ),
        migrations.AddField(
            model_name='shop',
            name='opictID',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='外見写真ID'),
        ),
    ]
