# Generated by Django 4.0.3 on 2022-11-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_owner_options_alter_owner_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'user', 'verbose_name_plural': 'owner'},
        ),
    ]
