# Generated by Django 4.0.3 on 2022-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_owner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='situation',
            field=models.IntegerField(choices=[(0, 'before'), (1, 'usable'), (2, 'used'), (3, 'refund')], default=0, verbose_name='状況'),
        ),
    ]
